import os

cwd = os.getcwd()

Import('env')
env.Append(CPPPATH=[cwd + '\STM32F4xx_HAL_Driver\Inc', cwd + '\CMSIS\Include', cwd + '\CMSIS\Device\ST\STM32F4xx\Include'])
# env.AppendUnique(CPPPATH = '')
# env.AppendUnique(CPPPATH = '')
# env.AppendUnique(CPPPATH = '')

objs = Glob('STM32F4xx_HAL_Driver\Src\*.c')

Return('objs')
